### ISSUE TITLE
Custom URL Protocol UDF

### ISSUE THREAD

**Issue by J2TeaM** [J2TeaM/awesome-AutoIt#8]
Cách đăng ký nhận UDF:

- [x] [Đăng ký tài khoản GitHub](https://github.com/join?source=junookyo.blogspot.com) (nếu chưa có).
- [x] Nhấn :star: Star tại [project](https://github.com/J2TeaM/awesome-AutoIt) này (cái nút ở góc phải phía trên ấy :wink:).
- [x] Để lại bình luận phía dưới với nội dung là URL Facebook hoặc địa chỉ email của bạn để mình gửi UDF qua.

**Comment by huynhvuthienloc** [comment]
huynhvuthienloc@gmail.com

**Comment by tutq9oo** [comment]
tutq9oo@gmail.com

**Comment by kentngoc** [comment]
dccxxcxix@gmail.com tks

**Comment by tqk2811** [comment]
tqk2811@yahoo.com.vn

**Comment by dacsang97** [comment]
dacsang97@gmail.com

**Comment by quandaica45** [comment]
hominhquanvn@gmail.com
Thanks you

**Comment by NguyenKhong** [comment]
Thanh.ng.cntt@gmail.com

**Comment by thai-baohoangthong** [comment]
xblackshadow2012@gmail.com

**Comment by ditimem19912010** [comment]
thieunghiemxuan@gmail.com  
Thanks you

**Comment by praolaanh** [comment]
https://www.facebook.com/NTL51

**Comment by anhgabeetouch** [comment]
https://www.facebook.com/tandang010

**Comment by caubenongthon321995** [comment]
https://www.facebook.com/luuquoc.minh96

**Comment by thedemons** [comment]
https://www.facebook.com/thedemonsmsc

**Comment by ghinlop** [comment]
ghinlop@gmail.com

**Comment by TricksyMan** [comment]
tricksyman@gmail.com

**Comment by thanhan7914** [comment]
thanhan7914@gmail.com

**Comment by J2TeaM** [comment]
Đã gửi mail cho các bạn! :wink:

**Comment by thedemons** [comment]
https://www.facebook.com/thedemonsmsc
hoặc thedemonsenc@gmail.com
Mình chưa nhận được nhỉ?

**Comment by caubenongthon321995** [comment]
nhận j???


2016-09-17 21:37 GMT+07:00 thedemons <notifications@github.com>:

**Comment by ptthan2k** [comment]
ptthan2k@gmail.com

**Comment by ngocthang26** [comment]
thangvl81@gmail.com

**Comment by ptthan2k** [comment]
Tks for reply

2016-09-24 13:27 GMT+07:00 ngocthang26 <notifications@github.com>:

**Comment by pnd280** [comment]
pndhcm280@gmail.com

Cám ơn J2TeaM đã chia sẻ (y) !

**Comment by phponline** [comment]
setivni@yahoo.com

Đã gắn * , Thanks J2Team

**Comment by vandatpro** [comment]
www.facebook.com/nhockm4v
đã *

**Comment by talata229** [comment]
tranquang229@gmail.com

**Comment by fizigeaykiri** [comment]
fizigeaykiri@gmail.com

**Comment by Kawaii93** [comment]
duyminh1136@gmail.com

**Comment by kid1232** [comment]
dttung48@gmail.com

**Comment by itfs1992** [comment]
nvv250292@gmail.com
